version: "3.8"

services:
    postgres:
        image: postgres:alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: database
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080